name: Auto UI Build and Publish
on:
  push:
    branches:
      - master
jobs:
  build_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
          registry: ${{ secrets.IMAGE_REGISTRY }}
          repository: ${{ secrets.IMAGE_REPO }}
          tag_with_ref: true
